##########################################################################################
#       Ultra Hardcore - Configuration file 
#
# ---
# If you want to have solo mode? Go to 'UhcConfig.TeamOptions.TeamMode' and type 'false'
#
# ---
# Minecraft Color Code:
#   &0  &1  &2  &3  &4      |       Black        Dark_Blue  Dark_Green  Dark_Aqua       Dark_Red
#   &5  &6  &7  &8  &9      |       Dark_Purple  Gold       Gray        Dark_Gray       Blue
#   &a  &b  &c  &d  &e      |       Green        Aqua       Red         Light_Purple    Yellow
#   &f  &k  &l  &m  &n      |       White        Magic      Bold        Strikethrough   Underline
#   &o  &r                  |       Italic       Reset
#

# --- Plugin Mode
Plugin: false

# --- Ultra Hardcore - Book
#
# Page Options
#   New line  ==  $[N]
#
UhcBook:
  Enabled: false
  ShowUhcConfig: false
  InventorySlot: 7
  BookName: '&eUltra Hardcore'
  BookLord:
  - ''
  - '&6- &7Info'
  - '&6- &7Rules'
  BookPages:
  - 'Welcome to &4&lUHC&0.$[N]$[N]This game you can only regenerate health by$[N] &8- &1Golden Apple&r$[N] &8- &1Potions.&r$[N]$[N]I wish you &5Good Luck&r$[N]and may the best player / team win.'
  - '&l&n    UHC - Rules     &r$[N]$[N]&11.&r Branch Mining$[N]&8 You can not branch$[N] mining but if you$[N] hear a sound,$[N] you can dig to it.&r$[N]$[N]&12. Staircases&r$[N]&8 You can only dig$[N] staircases if you$[N] want to find a cave.&r'
  
# --- Ultra Hardcore - Config
#
# Mark Options
#   Time     ==  $[T]
#   Episode  ==  $[E]
#
# Offline Kicker
#   Player ==  $[P]
#
UhcConfig:
  WorldOptions:
    ArenaSize: 1000
    SunStartTime: 0
  GameRules:
  - doDaylightCycle|true
  - randomTickSpeed|3
  WorldBorder:
    StartPos: 2500
    EndPos: 300
    Time: 10800
  MarkOptions:
    EveryMin: 20
    Message: '&cUHC&8 |&r YOU ARE NOW IN &a$[T]&r MIN IN'
  TeamOptions:
    TeamMode: false
    MaxPlayerInTeam: 3
    SelectTeamInventorySlot: 1
    TeamRules:
      friendlyfire: true
      seeFriendlyInvisibles: false
  DamagerLogger:
    Enabled: false
  OfflineKicker:
    MaxTimeout: 5
    Message: '$[P] was killed by Offline Timer'

# --- Global Chat Format
#
# Options
#   Player    ==  $[P]
#   Message  ==  $[M]
#
Chat:
  Default: '<$[P]> $[M]'
  Spectator: '<&7&o$[P]&r> $[M]'
  TeamMode:
    Default: '<&o$[P]&r> $[M]'
    Team: '<$[P]> $[M]'
